name: Initial Azure Setup

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

    - name: Reserved
      run: |
        ls -la
        az -v

      # Log into Azure
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

      # Deploy Bicep file
    - name: Deploy Bicep
      run: |
        az deployment sub create \
          --location "West Europe" \
          --name Testdeployment20221222 \
          --template-file ./01-build-your-modern-web-application/main.bicep \
          --parameters ./01-build-your-modern-web-application/parameters/main.parameters.json


        