on: [push]
name: Azure Deployment
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

    - name: Reserved
      run: |
        ls -la
        az -v

      # Log into Azure
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

       # Deploy Bicep file
    - name: Deploy Bicep
      run: |
        az deployment sub create \
          --location "West Europe" \
          --name Testdeployment20221222 \
          --template-file ./01-build-your-modern-web-application/main.bicep \
          --parameters ./01-build-your-modern-web-application/parameters/main.parameters.json



# npm run build
# az account set --subscription c34e7d41-2896-4edd-9386-9432283d9cb4



# The project was built assuming it is hosted at /.
# You can control this with the homepage field in your package.json.

# The build folder is ready to be deployed.
# You may serve it with a static server:

#   npm install -g serve
#   serve -s build

# Find out more about deployment here:

#   https://cra.link/deployment
