on: [push]
name: Azure ARM Deployment
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - name: Log in to Azure subscription
      if: env.subscription == 'Visual Studio Enterprise'
      uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./01-build-your-modern-web-application/main.bicep
        parameters: ./01-build-your-modern-web-application/parameters/main.parameters.json
        failOnStdErr: false